name: '✅ Verify PR'

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  git-town:
    runs-on: ubuntu-latest
    steps:
      - uses: git-town/action@v1.2.0
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sysdynetechnologies/.github/actions/node-install@master
      - run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sysdynetechnologies/.github/actions/node-install@master
      - run: pnpm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sysdynetechnologies/.github/actions/node-install@master
      - run: pnpm build
